'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("interfaz_de_usuario.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _53_534754_equipamiento_de_rayos_x_asistencia_tecnica_profesional_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("53-534754_equipamiento-de-rayos-x-asistencia-tecnica-profesional-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property de672573_3452_46de_839e_da7114759d62() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("de672573-3452-46de-839e-da7114759d62", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property descarga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("descarga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f1280x720_2366_134041_5050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f1280x720-2366_134041_5050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f1280x720_2366_134041_50501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f1280x720-2366_134041_50501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ff087c3a091148349d2983d33c461099() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ff087c3a091148349d2983d33c461099", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instagram_recuperación_cuenta_1080x675() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instagram-recuperación-cuenta-1080x675", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property istockphoto_675916976_170667a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-675916976-170667a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_clipart_password_strength_computer_security_password_policy_managed_security_service_procurement_icon_blue_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png-clipart-password-strength-computer-security-password-policy-managed-security-"& _ 
                        "service-procurement-icon-blue-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_clipart_password_strength_computer_security_password_policy_managed_security_service_procurement_icon_blue_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png-clipart-password-strength-computer-security-password-policy-managed-security-"& _ 
                        "service-procurement-icon-blue-logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property png_transparent_computer_icons_management_password_key_system_administrator_key_logo_monochrome_computer_program() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png-transparent-computer-icons-management-password-key-system-administrator-key-l"& _ 
                        "ogo-monochrome-computer-program", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property senal_de_evacuacion_flecha_izquierda_clase_b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("senal-de-evacuacion-flecha-izquierda-clase-b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spanishmexico_valorant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spanishmexico-valorant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transparent_hd_white_male_user_profile_icon_11637133256qticy7lqml() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent-hd-white-male-user-profile-icon-11637133256qticy7lqml", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transparent_hd_white_male_user_profile_icon_11637133256qticy7lqml1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparent-hd-white-male-user-profile-icon-11637133256qticy7lqml1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_ray_1704855_1280() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-ray-1704855_1280", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_ray_1704855_12801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-ray-1704855_12801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
